# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean
    increment_build_number(xcodeproj: "OddMusiq.xcodeproj")


    build_app(scheme: "OddMusiq")
    
    api_key = app_store_connect_api_key(
      key_id: "5U3LUYFKQY",
      issuer_id: "69a6de91-770f-47e3-e053-5b8c7c11a4d1",
      key_filepath: "~/.private_keys/AuthKey_5U3LUYFKQY.p8"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )

    commit_version_bump(xcodeproj: "OddMusiq.xcodeproj")
    add_git_tag
    push_to_git_remote
    reset_git_repo(skip_clean: true)
    clean_build_artifacts
  end
end
