# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

ARTIFACTS_PATH = "./build/artifacts/"

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean
    increment_build_number(xcodeproj: "OddMusiq.xcodeproj")

    build_app(
      configuration: "Release",
      clean: true,
      xcargs: "-skipPackagePluginValidation -allowProvisioningUpdates OTHER_SWIFT_FLAGS='$(inherited) -D INTERNAL_BUILD'",
      scheme: "OddMusiq",
      output_directory: ARTIFACTS_PATH,
    )
    
    api_key = app_store_connect_api_key(
      key_id: "5U3LUYFKQY",
      issuer_id: "69a6de91-770f-47e3-e053-5b8c7c11a4d1",
      key_filepath: "~/.private_keys/AuthKey_5U3LUYFKQY.p8"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )

    # add_git_tag
    # push_to_git_remote
    reset_git_repo(skip_clean: true)
    clean_build_artifacts
  end

  desc "Ad Hoc Distribution"
  lane :adhoc do
    ensure_git_status_clean
    increment_build_number(xcodeproj: "OddMusiq.xcodeproj")

    build_app(
      configuration: "Alpha",
      clean: true,
      xcargs: "-skipPackagePluginValidation -allowProvisioningUpdates OTHER_SWIFT_FLAGS='$(inherited) -D INTERNAL_BUILD'",
      scheme: "OddMusiq",
      export_method: "ad-hoc",
      output_directory: ARTIFACTS_PATH,
    )

    # add_git_tag
    # push_to_git_remote
    reset_git_repo(skip_clean: true)
    clean_build_artifacts
  end
  
  desc "Run test"
  lane :test do
    run_tests(
      devices: ["iPhone 15"],
    )
  end 
end
